
```{r}
#############################################################################################################
##
## STARTUP CODE TO LOAD LIBRARIES AND DATA
## 
## NO TEXT
##
###############################################################################################################
```


```{r load-libraries}
# Load libraries
library(tidyverse)
library(gridExtra)
library(kableExtra)
library(lubridate)

library(dslabs)
ds_theme_set()

```

```{r load-dataset-from-disk}
# LendingClub data
if (!exists("lending_club")) lending_club <- readRDS("datasets/lending_club_reformatted.rds")
if (!exists("loans")) loans <- readRDS("datasets/lending_club_reformatted_paid.rds")

# Response variables
if (!exists("LoansIRR")) LoansIRR <- read.csv("datasets/LoanIRR.csv") %>% as_tibble()
if (!exists("LoanMargin")) LoanMargin <- read.csv("datasets/CreditMargins.csv") %>% as_tibble()

# Interest rate swaps
if (!exists("RATES")) RATES <- readRDS("datasets/rates.rds")
if (!exists("RATES3Y")) RATES3Y <- readRDS("datasets/rates3Y.rds")
if (!exists("RATES5Y")) RATES5Y <- readRDS("datasets/rates5Y.rds")

# ZIP/FIPS code data
if (!exists("zips")) zips <- readRDS("datasets/zips.rds")
if (!exists("zipfips")) zipfips <- readRDS("datasets/kaggleCodes.rds")

# Macro data
if (!exists("medianIncome")) medianIncome <- readRDS("datasets/medianincome.rds")
if (!exists("personalIncome")) personalIncome <- readRDS("datasets/personalincome.rds")
if (!exists("unemploymentRate")) unemploymentRate <- readRDS("datasets/unemployment.rds")


```



```{r needed-functions}
############################################################################################################
##
## Given a date and a 3-digit zip, returns a triplet of:
##  - the unemployment rate
##  - the median income
##  - personal income
## for that ZIP.
##
## The indicators are published by FIPS (Federal Information Processing Standard state code). A ZIP code
## can cover several FIPS. In such a case, the function looks up all the relevant FIPS code and returns
## a population weighted average of the indicators.
##
##

indicatorsFromZIPandDate <- function(zip3d, application_date) {
  require(tidyverse)
  require(lubridate)
  
  emptyResult <-
    tibble(
      unemployment = 0,
      medianIncome = 0,
      personalIncome = 0
    )
  
  
  if (!is.numeric(zip3d))
    return(emptyResult)
  if (!is.Date(application_date))
    return(emptyResult)
  
  # Get all the FIPS with population
  populatedzips <- zipfips %>%
    # Look up a specific zip
    filter(zip == zip3d) %>%
    select(zip, population, county_fips) %>%
    
    # Rename the FIPS column
    rename(FIPS = county_fips) %>%
    
    # Add the population of all the counties with the same FIPS
    group_by(FIPS) %>%
    mutate(population = sum(population)) %>%
    
    # And keep unique zip/FIPS pairs with its population
    distinct(FIPS, .keep_all = TRUE)
  
  
  # Get macro stats
  ratePerFIPS <- unemploymentRate %>%
    # filter for FIPS
    filter(FIPS %in% populatedzips$FIPS) %>%
    
    # And all dates before the application date
    filter(application_date >= Date) %>%
    
    # Sort the dates in decreasing order
    arrange(desc(Date)) %>%
    
    # So that we only keep the first one
    distinct(FIPS, .keep_all = TRUE)
  
  medianPerFIPS <- medianIncome %>%
    filter(FIPS %in% populatedzips$FIPS) %>%
    filter(application_date >= Date) %>%
    arrange(desc(Date)) %>%
    distinct(FIPS, .keep_all = TRUE)
  
  personalPerFIPS <- personalIncome %>%
    filter(FIPS %in% populatedzips$FIPS) %>%
    filter(application_date >= Date) %>%
    arrange(desc(Date)) %>%
    distinct(FIPS, .keep_all = TRUE)
  
  # Put it all back together
  summ <- populatedzips %>%
    left_join(ratePerFIPS, by = "FIPS") %>%
    left_join(medianPerFIPS, by = "FIPS") %>%
    left_join(personalPerFIPS, by = "FIPS") %>%
    mutate_at(c("unemploymentRate", "medianIncome", "personalIncome"),
              as.double)
  
  # And return
  tibble(
    unemployment = sum(summ$population * summ$unemploymentRate) / (sum(summ$population)),
    medianIncome = sum(summ$population * summ$medianIncome) / (sum(summ$population)),
    personalIncome = sum(summ$population * summ$personalIncome) / (sum(summ$population))
  )
}


###################################################################################################
#
# Given some numerical parameters describing a loan in the dataset, returns its Internal Rate
# of Return.
#
# In the first instance, the function creates a schedule of payments.
# In many cases, the schedule will be extremely simple: a series of 36 or 60 equal instalements.
#
# But in some cases, a loan repayment are accelerated. Therefore the total amount of interest will
# be lower than expected (but this is good for the investor because highe interest rate over
# shorter tenor.).
#
# In other cases, the borrower defaults. Overall payments are less than expected.
#
# Based on the limited information of the dataset, the function makes educated guesses on the exact schedule.
#
# WARNING: THIS IS NOT OPTIMISED. RUNNING THIS FOR ALL LOANS (1.3 MLN OF THEM) TAKES CA.20 HOURS !!!!
#
calculateIRR <- function(loanNumber = 1,
                         loan,
                         intRate,
                         term = 36,
                         totalPaid,
                         totalPrincipalPaid,
                         totalInterestPaid,
                         recoveries = 0,
                         lateFees = 0,
                         showSchedule = FALSE) {
  require(tidyverse)
  
  # number of monthly payments.
  # It exceeds 60 months in case recoveries on a 60-month loan takes the schedule after 60 months.
  nMonths <- 90
  
  # Months after which a loan defaults (normal tenor if no default or early prepayment)
  monthDefault = term
  
  # Note: *100 /100 to calculate in cent because ceiling cannot specify significant digits.
  installment <-
    ceiling(100 * loan * intRate / 12 / (1 - 1 / (1 + intRate / 12) ^ term)) / 100
  
  # We create a schedule
  schedule <- tibble(
    month = 0:nMonths,
    monthlyPayment = 0.0,
    totalPandI = 0.0,
    totalI = 0.0,
    totalP = 0.0
  )
  
  for (i in 2:(nMonths + 2)) {
    # Get situation at the end of previous month
    previousTotalPandI <- as.numeric(schedule[i - 1, "totalPandI"])
    previousTotalP     <- as.numeric(schedule[i - 1, "totalP"])
    previousTotalI     <- as.numeric(schedule[i - 1, "totalI"])
    
    # This is the beginning of a new month. First and foremost, the borrower is expected to pay the
    # accrued interest on amount of principal outstanding.
    # ceiling doesn't seem accept to accept significative digits.
    accruedInterest <-
      ceiling(100 * (loan - previousTotalP) * intRate / 12) / 100
    
    # If that amount takes the schedule above the total amount of interest shown in the data set,
    # we should stop the schedule at this point
    if (previousTotalI + accruedInterest > totalInterestPaid) {
      # We stop the normal schedule at this date.
      # Interest is paid (although less than scheduled)
      schedule[i, "monthlyPayment"] <-
        totalInterestPaid - previousTotalI
      
      # As well as whatever principal is left as per the dataset
      schedule[i, "monthlyPayment"] <-
        schedule[i, "monthlyPayment"] + totalPrincipalPaid - previousTotalP
      
      # Then 3-month after the last payment date, recoveries and and later fees are paid
      schedule[i + 3, "monthlyPayment"] <-
        schedule[i + 3, "monthlyPayment"] + recoveries + lateFees
      
      # Not really useful, but for completeness
      schedule[i, "totalPandI"] <- totalPaid
      schedule[i, "totalI"]     <- totalInterestPaid
      schedule[i, "totalP"]     <- totalPrincipalPaid
      
      # If total principal paid is less than borrower, then it is a default, and the monthDefault
      # is adjusted.
      if (totalPrincipalPaid < loan) {
        monthDefault = i
      }
      
      # No more payments to add to the schedule
      break()
      
    } else {
      # Deal with normal schedule
      schedule[i, "monthlyPayment"] <- installment
      schedule[i, "totalPandI"] <-
        schedule[i - 1, "totalPandI"] + installment
      schedule[i, "totalI"]     <-
        schedule[i - 1, "totalI"]   + accruedInterest
      schedule[i, "totalP"]     <-
        schedule[i - 1, "totalP"]   + installment - accruedInterest
    }
  }
  
  # At this point schedule[, "monthlyPayment"] contains the schedule of all payments, but needs to
  # include the initial loan.
  schedule[1, "monthlyPayment"] <- -loan
  
  if (showSchedule) {
    schedule %>% view()
  }
  
  NPV <- function(interest, cashFlow) {
    t = 0:(length(cashFlow) - 1)
    sum(cashFlow / (1 + interest) ^ t)
  }
  
  IRR <- function(CF) {
    res <- NA
    try({
      res <- uniroot(NPV, c(-0.9, 1), cashFlow = CF)$root
    },
    silent = TRUE)
    return(res)
  }
  
  return(tibble(
    loanID = loanNumber,
    IRR = round(as.numeric(IRR(
      schedule$monthlyPayment
    ) * 12), digits = 4),
    monthDefault = monthDefault
  ))
}

loanNumberIRR <- function(loanNumber) {
  require(tidyverse)
  
  l <- loans %>% filter(loanID == loanNumber)
  calculateIRR(
    loanNumber = l$loanID,
    loan = l$funded_amnt, intRate = l$int_rate, term = l$term, 
    totalPaid = l$total_pymnt, totalPrincipalPaid = l$total_rec_prncp, totalInterestPaid = l$total_rec_int, 
    recoveries = l$recoveries, lateFees = l$total_rec_late_fee, 
    showSchedule = TRUE
  )
}


```



```{r list-of-variables}
# Mostly generated from a LibreOffice spreadsheet for convenience purposes, then reformatted by RStudio.

LC_variable <-
  tibble(
    variable_name = 'loanID' ,
    description = 'NOTE THIS IS NOT AN ORIGINAL VARIABLE. IT WAS ADDED FOR THE PURPOSE OF TRACKING LOANS INDIVIDUALLY AS AND WHEN NEEDED.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'loan_amnt' ,
    description = 'The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'funded_amnt' ,
    description = 'The total amount committed to that loan at that point in time.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'funded_amnt_inv' ,
    description = 'The total amount committed by investors for that loan at that point in time.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'term' ,
    description = 'The number of payments on the loan. Values are in months and can be either 36 or 60.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'int_rate' ,
    description = 'Interest Rate on the loan',
    inModel = TRUE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'installment' ,
    description = 'The monthly payment owed by the borrower if the loan originates.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'grade' ,
    description = 'LC assigned loan grade',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sub_grade' ,
    description = 'LC assigned loan subgrade',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'emp_title' ,
    description = 'The job title supplied by the Borrower when applying for the loan.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'emp_length' ,
    description = 'Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years. ',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'home_ownership' ,
    description = 'The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER, NONE',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'annual_inc' ,
    description = 'The self-reported annual income provided by the borrower during registration. NOT USED AS A VARIABLE SINCE JOINT INCOME ALREADY INCLUDES IT.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'verification_status' ,
    description = 'Indicates if income was verified by LC, not verified, or if the income source was verified',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'issue_d' ,
    description = 'The month which the loan was funded',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'loan_status' ,
    description = 'Current status of the loan',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'pymnt_plan' ,
    description = 'Indicates if a payment plan has been put in place for the loan',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'url' ,
    description = 'URL for the LC page with listing data.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'desc' ,
    description = 'Loan description provided by the borrower',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'purpose' ,
    description = 'A category provided by the borrower for the loan request. ',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'title' ,
    description = 'The loan title provided by the borrower',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'zip_code' ,
    description = 'The first 3 numbers of the zip code provided by the borrower in the loan application.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'addr_state' ,
    description = 'The state provided by the borrower in the loan application',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'dti' ,
    description = 'A ratio calculated using the borrower s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower s self-reported monthly income. NOT USED AS A VARIABLE. ONLY USE JOINT DTI.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'delinq_2yrs' ,
    description = 'The number of 30+ days past-due incidences of delinquency in the borrower s credit file for the past 2 years',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'earliest_cr_line' ,
    description = 'The month the borrower s earliest reported credit line was opened',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'inq_last_6mths' ,
    description = 'The number of inquiries in past 6 months (excluding auto and mortgage inquiries)',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mths_since_last_delinq' ,
    description = 'The number of months since the borrower s last delinquency.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mths_since_last_record' ,
    description = 'The number of months since the last public record.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'open_acc' ,
    description = 'The number of open credit lines in the borrower s credit file.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'pub_rec' ,
    description = 'Number of derogatory public records',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'revol_bal' ,
    description = 'Total credit revolving balance',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'revol_util' ,
    description = 'Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'total_acc' ,
    description = 'The total number of credit lines currently in the borrower s credit file',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'initial_list_status' ,
    description = 'The initial listing status of the loan. Possible values are – W, F',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'out_prncp' ,
    description = 'Remaining outstanding principal for total amount funded. NOTE ONCE A LOAN IS REPAID OR CHARGED OFF, THIS AMOUNT BECOMES 0. ',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'out_prncp_inv' ,
    description = 'Remaining outstanding principal for portion of total amount funded by investors. NOTE ONCE A LOAN IS REPAID OR CHARGED OFF, THIS AMOUNT BECOMES 0. ',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'total_pymnt' ,
    description = 'Payments received to date for total amount funded',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'total_pymnt_inv' ,
    description = 'Payments received to date for portion of total amount funded by investors',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'total_rec_prncp' ,
    description = 'Principal received to date. NOTE THIS AMOUNT WILL SHOW WHETHER A BORROWER DID NOT REPAY IN FULL',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'total_rec_int' ,
    description = 'Interest received to date',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'total_rec_late_fee' ,
    description = 'Late fees received to date',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'recoveries' ,
    description = 'Post charge off gross recovery. NOTE IF A LOAN IS REPAID, THIS AMOUNT IS 0. ',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'collection_recovery_fee' ,
    description = 'Post charge off collection fee',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'last_pymnt_d' ,
    description = 'Last month payment was received',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'last_pymnt_amnt' ,
    description = 'Last total payment amount received',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'next_pymnt_d' ,
    description = 'Next scheduled payment date',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'last_credit_pull_d' ,
    description = 'The most recent month LC pulled credit for this loan',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'collections_12_mths_ex_med' ,
    description = 'Number of collections in 12 months excluding medical collections',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mths_since_last_major_derog' ,
    description = 'Months since most recent 90-day or worse rating',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'policy_code' ,
    description = 'Publicly available policy_code=1 / New products not publicly available policy_code=2',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'application_type' ,
    description = 'Indicates whether the loan is an individual application or a joint application with two coborrowers',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'annual_inc_joint' ,
    description = 'The combined self-reported annual income provided by the coborrowers during registration',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'dti_joint' ,
    description = 'A ratio calculated using the coborrowers total monthly payments on the total debt obligations, excluding mortgages and the requested LC loan, divided by the coborrowers combined self-reported monthly income',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'verification_status_joint' ,
    description = 'Indicates if income was verified by LC, not verified, or if the income source was verified',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'acc_now_delinq' ,
    description = 'The number of accounts on which the borrower is now delinquent.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'tot_coll_amt' ,
    description = 'Total collection amounts ever owed',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'tot_cur_bal' ,
    description = 'Total current balance of all accounts',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'open_acc_6m' ,
    description = 'Number of open trades in last 6 months',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'open_act_il' ,
    description = 'Number of currently active installment trades',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'open_il_12m' ,
    description = 'Number of installment accounts opened in past 12 months',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'open_il_24m' ,
    description = 'Number of installment accounts opened in past 24 months',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'mths_since_rcnt_il' ,
    description = 'Months since most recent instalment accounts opened',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'total_bal_il' ,
    description = 'Total current balance of all installment accounts',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'il_util' ,
    description = 'Ratio of total current balance to high credit/credit limit on all install acct',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'open_rv_12m' ,
    description = 'Number of revolving trades opened in past 12 months',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'open_rv_24m' ,
    description = 'Number of revolving trades opened in past 24 months',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'max_bal_bc' ,
    description = 'Maximum current balance owed on all revolving accounts',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'all_util' ,
    description = 'Balance to credit limit on all trades',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'total_rev_hi_lim' ,
    description = 'Total revolving high credit/credit limit',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'inq_fi' ,
    description = 'Number of personal finance inquiries',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'total_cu_tl' ,
    description = 'Number of finance trades',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'inq_last_12m' ,
    description = 'Number of credit inquiries in past 12 months',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'acc_open_past_24mths' ,
    description = 'Number of trades opened in past 24 months.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'avg_cur_bal' ,
    description = 'Average current balance of all accounts',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'bc_open_to_buy' ,
    description = 'Total open to buy on revolving bankcards.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'bc_util' ,
    description = 'Ratio of total current balance to high credit/credit limit for all bankcard accounts.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'chargeoff_within_12_mths' ,
    description = 'Number of charge-offs within 12 months',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'delinq_amnt' ,
    description = 'The past-due amount owed for the accounts on which the borrower is now delinquent.',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'mo_sin_old_il_acct' ,
    description = 'Months since oldest bank instalment account opened',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mo_sin_old_rev_tl_op' ,
    description = 'Months since oldest revolving account opened',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mo_sin_rcnt_rev_tl_op' ,
    description = 'Months since most recent revolving account opened',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mo_sin_rcnt_tl' ,
    description = 'Months since most recent account opened',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mort_acc' ,
    description = 'Number of mortgage accounts.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mths_since_recent_bc' ,
    description = 'Months since most recent bankcard account opened.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mths_since_recent_bc_dlq' ,
    description = 'Months since most recent bankcard delinquency',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mths_since_recent_inq' ,
    description = 'Months since most recent inquiry.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'mths_since_recent_revol_delinq' ,
    description = 'Months since most recent revolving delinquency.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_accts_ever_120_pd' ,
    description = 'Number of accounts ever 120 or more days past due',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_actv_bc_tl' ,
    description = 'Number of currently active bankcard accounts',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_actv_rev_tl' ,
    description = 'Number of currently active revolving trades',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_bc_sats' ,
    description = 'Number of satisfactory bankcard accounts',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_bc_tl' ,
    description = 'Number of bankcard accounts',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_il_tl' ,
    description = 'Number of installment accounts',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_op_rev_tl' ,
    description = 'Number of open revolving accounts',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_rev_accts' ,
    description = 'Number of revolving accounts',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_rev_tl_bal_gt_0' ,
    description = 'Number of revolving trades with balance >0',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_sats' ,
    description = 'Number of satisfactory accounts',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_tl_120dpd_2m' ,
    description = 'Number of accounts currently 120 days past due (updated in past 2 months)',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_tl_30dpd' ,
    description = 'Number of accounts currently 30 days past due (updated in past 2 months)',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_tl_90g_dpd_24m' ,
    description = 'Number of accounts 90 or more days past due in last 24 months',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'num_tl_op_past_12m' ,
    description = 'Number of accounts opened in past 12 months',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'pct_tl_nvr_dlq' ,
    description = 'Percent of trades never delinquent',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'percent_bc_gt_75' ,
    description = 'Percentage of all bankcard accounts > 75% of limit.',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'pub_rec_bankruptcies' ,
    description = 'Number of public record bankruptcies',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'tax_liens' ,
    description = 'Number of tax liens',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'tot_hi_cred_lim' ,
    description = 'Total high credit/credit limit',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'total_bal_ex_mort' ,
    description = 'Total credit balance excluding mortgage',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'total_bc_limit' ,
    description = 'Total bankcard high credit/credit limit',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'total_il_high_credit_limit' ,
    description = 'Total installment high credit/credit limit',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'revol_bal_joint' ,
    description = 'Total credit revolving balance',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_earliest_cr_line' ,
    description = 'Earliest credit line at time of application for the secondary applicant. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_inq_last_6mths' ,
    description = 'Credit inquiries in the last 6 months at time of application for the secondary applicant. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_mort_acc' ,
    description = 'Number of mortgage accounts at time of application for the secondary applicant. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_open_acc' ,
    description = 'Number of open trades at time of application for the secondary applicant. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_revol_util' ,
    description = 'Ratio of total current balance to high credit/credit limit for all revolving accounts. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_open_act_il' ,
    description = 'Number of currently active installment trades at time of application for the secondary applicant. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_num_rev_accts' ,
    description = 'Number of revolving accounts at time of application for the secondary applicant. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_chargeoff_within_12_mths' ,
    description = 'Number of charge-offs within last 12 months at time of application for the secondary applicant. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_collections_12_mths_ex_med' ,
    description = 'Number of collections within last 12 months excluding medical collections at time of application for the secondary applicant. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'sec_app_mths_since_last_major_derog' ,
    description = 'Months since most recent 90-day or worse rating at time of application for the secondary applicant. VARIABLE NOT USED. WE RELY ON THE MAIN BORROWER IN THE FIRST INSTANCE.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'hardship_flag' ,
    description = 'Flags whether or not the borrower is on a hardship plan',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'hardship_type' ,
    description = 'Describes the hardship plan offering',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'hardship_reason' ,
    description = 'Describes the reason the hardship plan was offered',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'hardship_status' ,
    description = 'Describes if the hardship plan is active, pending, cancelled, completed, or broken',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'deferral_term' ,
    description = 'Amount of months that the borrower is expected to pay less than the contractual monthly payment amount due to a hardship plan',
    inModel = FALSE,
    inPrediction = TRUE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'hardship_amount' ,
    description = 'The interest payment that the borrower has committed to make each month while they are on a hardship plan',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'hardship_start_date' ,
    description = 'The start date of the hardship plan period',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'hardship_end_date' ,
    description = 'The end date of the hardship plan period',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'payment_plan_start_date' ,
    description = 'The day the first hardship plan payment is due. For example, if a borrower has a hardship plan period of 3 months, the start date is the start of the three-month period in which the borrower is allowed to make interest-only payments.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'hardship_length' ,
    description = 'The number of months the borrower will make smaller payments than normally obligated due to a hardship plan',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'hardship_dpd' ,
    description = 'Account days past due as of the hardship plan start date',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'hardship_loan_status' ,
    description = 'Loan Status as of the hardship plan start date',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'orig_projected_additional_accrued_interest' ,
    description = 'The original projected additional interest amount that will accrue for the given hardship payment plan as of the Hardship Start Date. This field will be null if the borrower has broken their hardship payment plan.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'hardship_payoff_balance_amount' ,
    description = 'The payoff balance amount as of the hardship plan start date',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'hardship_last_payment_amount' ,
    description = 'The last payment amount as of the hardship plan start date',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = TRUE
  ) %>%
  add_row(
    variable_name = 'disbursement_method' ,
    description = 'The method by which the borrower receives their loan. Possible values are: CASH, DIRECT_PAY',
    inModel = TRUE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'debt_settlement_flag' ,
    description = 'Flags whether or not the borrower, who has charged-off, is working with a debt-settlement company.',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'debt_settlement_flag_date' ,
    description = 'The most recent date that the Debt_Settlement_Flag has been set  ',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'settlement_status' ,
    description = 'The status of the borrower’s settlement plan. Possible values are: COMPLETE, ACTIVE, BROKEN, CANCELLED, DENIED, DRAFT',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'settlement_date' ,
    description = 'The date that the borrower agrees to the settlement plan',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'settlement_amount' ,
    description = 'The loan amount that the borrower has agreed to settle for',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'settlement_percentage' ,
    description = 'The settlement amount as a percentage of the payoff balance amount on the loan',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  ) %>%
  add_row(
    variable_name = 'settlement_term' ,
    description = 'The number of months that the borrower will be on the settlement plan',
    inModel = FALSE,
    inPrediction = FALSE,
    inPricing = FALSE
  )
```
